src/Entity/Partner.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartnersRepository")
 */
class Partner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logoFilename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLogoFilename(): ?string
    {
        return $this->logoFilename;
    }

    public function getLogoPath()
    {
        return 'images/partners/'.$this->getLogoFilename();
    }

    public function setLogoFilename(string $logoFilename): self
    {
        $this->logoFilename = $logoFilename;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }
}

src/Controller/AboutController.php
<?php

namespace App\Controller;

use App\Repository\PartnersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AboutController extends BaseController
{
    /**
     * @Route("/about/main", name="app_about")
     */
    public function about(Request $request, PartnersRepository $partnersRepository)
    {
        $partners = $partnersRepository->findAll();

        $this->contactUsHandleForm($request);
        // todo dynamic data for department member
        return $this->render('about/about.html.twig', [
            'partners' => $partners
        ]);
    }

    /**
     * @Route("/about/agricultural-engineering", name="app_history-ae")
     */
    public function equipmentHistory(Request $request)
    {
        $this->contactUsHandleForm($request);
        return $this->render("about/history_ae.html.twig");
    }

    /**
     * @Route("/about/cars-and-tractors", name="app_history-ct")
     */
    public function carsHistory(Request $request)
    {
        $this->contactUsHandleForm($request);
        return $this->render("about/history_ct.html.twig");
    }


    /**
     * @Route("/about/partners", name="app_partners")
     */
    public function ourPartners(Request $request, PartnersRepository $partnersRepository)
    {
        $partners = $partnersRepository->findAll();

        $this->contactUsHandleForm($request);
        // todo getPartners
        return $this->render("about/partners.html.twig", [
            'partners' => $partners
        ]);
    }
}

templates/about/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}О кафедре{% endblock %}

{% block body %}

    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-graduation-cap',
        title: 'О кафедре'
    }) }}

    <section class="section novi-background section-98 section-sm-110">
        <div class="container">
            <div class="row justify-content-sm-center">
                <div class="col-sm-10 col-md-5 col-xl-4 text-lg-left">
                    <!-- Member Block Type 5-->
                    <div class="member-block-type-5 inset-lg-right-30"><img class="img-fluid d-block mx-auto" src="{{ asset('images/users/user-john-doe-437x437.jpg') }}" width="437" height="437" alt="">
                        <div class="member-block-body text-center"><a class="btn btn-block btn-primary" href="#">Подробнее</a>
                            <div class="offset-top-24 offset-lg-top-20 text-center">
                                <div><span class="novi-icon icon icon-xxs text-middle mdi mdi-cellphone-android text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="tel:#">8 (3852) 29-08-15</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-email-open text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="mailto:#">korsan73@mail.ru</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-map-marker-circle"></span>&ensp;<span class="text-middle text-dark">Аудитория: 308a B</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-10 text-md-left col-md-7 col-xl-8 offset-top-24 offset-md-top-0">
                    <h3>КОРОСТЕЛЕВ СЕРГЕЙ АНАТОЛЬЕВИЧ</h3>
                    <div>
                        <h3 class="small text-darker">ЗАВЕДУЮЩИЙ КАФЕДРОЙ</h3>
                        <p class="small text-darker">доктор теxнических наук, доцент</p>
                    </div>
                    <hr class="text-subline offset-top-10 offset-md-top-30">
                    <div class="offset-top-24 offset-lg-top-0">
                        <p class="text-left">
                            I am a senior advisor for an independently owned financial planning company called Intense. We are an International Financial Planning company with offices in multiple jurisdictions over the world. Working with Intense gives me the ability to advise business owners all over the world via Internet or personally in the area of my location.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, aliquam aperiam assumenda blanditiis debitis doloremque esse, ex id, itaque modi molestiae non odio praesentium quod soluta temporibus vitae? Amet dolorem nihil pariatur sunt velit. Eum ipsam provident sint! At commodi dignissimos dolorum eligendi quisquam sapiente voluptatem voluptatibus? Dolor, eaque non!
                           esse et laudantium quo rerum?
                        </p>
                    </div>
                    <div class="offset-top-24 offset-lg-top-24">
                        <p class="text-left">
                            I am a senior advisor for an independently owned financial planning company called Intense. We are an International Financial Planning company with offices in multiple jurisdictions over the world. Working with Intense gives me the ability to advise business owners all over the world via Internet or personally in the area of my location.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, aliquam aperiam assumenda blanditiis debitis doloremque esse, ex id, itaque modi molestiae non odio praesentium quod soluta temporibus vitae? Amet dolorem nihil pariatur sunt velit. Eum ipsam provident sint! At commodi dignissimos dolorum eligendi quisquam sapiente voluptatem voluptatibus? Dolor, eaque non!
                            esse et laudantium quo rerum?
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- section reasons to get-->
    <section class="section novi-background section-66 section-top-50 bg-mantis section-triangle section-triangle-bottom context-dark">
        <div class="container">
            <div class="row justify-content-md-center">
                <h2><span class="big">Немного истории</span></h2>
                <div class="col-lg-12">
                    <p>Кафедра образована 01.07.2014 г. в результате объединения кафедр «Автомобили и тракторы» и «Сельскохозяйственное машиностроение».</p>
                </div>
            </div>
        </div>
        <svg class="svg-triangle-bottom" xmlns="http://www.w3.org/2000/svg" version="1.1">
            <defs>
                <lineargradient id="grad2" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" style="stop-color:rgb(99,189,98);stop-opacity:1"></stop>
                    <stop offset="100%" style="stop-color:rgb(99,189,98);stop-opacity:1"></stop>
                </lineargradient>
            </defs>
            <polyline points="0,0 60,0 29,29" fill="url(#grad2)"></polyline>
        </svg>
    </section>
    <section class="section novi-background section-66 section-sm-0">
        <div class="container">
            <div class="row justify-content-sm-center justify-content-md-start">
                <div class="col-sm-10 col-md-6 section-image-aside section-image-aside-right text-left">
                    <div class="section-image-aside-img d-none d-md-block" style="background-image: url({{ asset('images/careers-01-960x540.jpg') }})"></div>
                    <div class="section-image-aside-body section-sm-66 inset-md-right-30">
                        <div>
                            <h3 class="text-picton-blue">01</h3>
                        </div>
                        <div class="offset-top-10">
                            <h2>Кафедра осуществляет подготовку по специальности 23.05.01 Наземные транспортно-технологические средства.</h2>
                        </div>
                        <div class="offset-top-20">
                            <p>По специализациям:

                                Автомобили и тракторы;
                                Технические средства агропромышленного комплекса.
                                Нормативный срок обучения — 5 лет (дневная форма обучения).

                                Квалификация  — специалист.</p>
                            <p>Характеристика специальности.
                                Выпускник обладает знаниями в области проектирования, производства, испытания, эксплуатации, ремонта и технического обслуживания автомобилей и тракторов, сельскохозяйственных машин и оборудования.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-sm-center justify-content-md-end offset-top-0">
                <div class="col-sm-10 col-md-6 section-image-aside section-image-aside-left text-left">
                    <div class="section-image-aside-img d-none d-md-block" style="background-image: url({{ asset('images/careers-02-960x540.jpg') }})"></div>
                    <div class="section-image-aside-body offset-top-41 offset-md-top-0 section-sm-66 inset-md-left-50">
                        <div>
                            <h3 class="text-picton-blue">02</h3>
                        </div>
                        <div class="offset-top-10">
                            <h2>Объектами профессиональной деятельности специалиста являются</h2>
                        </div>
                        <div class="offset-top-20">
                           <p>автомобили, тракторы, автомобильные и тракторные прицепы и полуприцепы,  технические средства агропромышленного комплекса, подъёмно-транспортные, строительные, дорожные средства и оборудование, нормативно-техническая документация, системы стандартизации, методы и средства испытаний и контроля качества изделий.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-sm-center justify-content-md-start offset-top-0">
                <div class="col-sm-10 col-md-6 section-image-aside section-image-aside-right text-left">
                    <div class="section-image-aside-img d-none d-md-block" style="background-image: url({{ asset('images/careers-03-960x540.jpg') }})"></div>
                    <div class="section-image-aside-body offset-top-41 offset-md-top-0 section-sm-66 inset-md-right-30">
                        <div>
                            <h3 class="text-picton-blue">03</h3>
                        </div>
                        <div class="offset-top-10">
                            <h2>Виды профессиональной деятельности:</h2>
                        </div>
                        <div class="offset-top-20">
                            <p>научно-исследовательская;
                                проектно-конструкторская;
                                производственно-технологическая;
                                организационно-управленческая.</p>
                            <p>Преподаватели кафедры имеют ученые степени кандидата технических наук и звания доцента. Сотрудники кафедры занимаются научно-исследовательской работой и регулярно принимают участие в научно-технических конференциях в ведущих ВУЗах России.
                                Кафедра располагает современными лабораториями.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-sm-center justify-content-md-end offset-top-0">
                <div class="col-sm-10 col-md-6 section-image-aside section-image-aside-left text-left">
                    <div class="section-image-aside-img d-none d-md-block" style="background-image: url({{ asset('images/careers-04-960x540.jpg') }})"></div>
                    <div class="section-image-aside-body offset-top-41 offset-md-top-0 section-sm-66 inset-md-left-50">
                        <div>
                            <h3 class="text-picton-blue">04</h3>
                        </div>
                        <div class="offset-top-10">
                            <h2>Место будущей работы:</h2>
                        </div>
                        <div class="offset-top-20">
                            <p>автомобильные и тракторные заводы, заводы сельскохозяйственного машиностроения, автотранспортные предприятия, станции технического обслуживания автомобилей и тракторов, авторемонтные заводы, дилерские центры, управления механизации дорожных и строительных компаний, пункты проведения инструментального контроля транспортных средств (техосмотр).</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- section career start here-->
    <section class="section novi-background section-66 section-top-50 bg-blue-gray section-triangle section-triangle-bottom context-dark" id="careers-start">
        <div class="container">
            <h2><span class="big">Возможности студентов</span></h2>
            <p>Студентны нашей кафедры имеют возможность проходить производственную практику</p>
        </div>
        <svg class="svg-triangle-bottom" xmlns="http://www.w3.org/2000/svg" version="1.1">
            <defs>
                <lineargradient id="grad3" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" style="stop-color:rgb(109,146,204);stop-opacity:1"></stop>
                    <stop offset="100%" style="stop-color:rgb(109,146,204);stop-opacity:1"></stop>
                </lineargradient>
            </defs>
            <polyline points="0,0 60,0 29,29" fill="url(#grad3)"></polyline>
        </svg>
    </section>

    <section class="section novi-background section-98 section-sm-110 section-sm-top-50">
        <div class="container">
            <div class="row justify-content-sm-center align-items-xl-center offset-top-20">
                <div class="col-md-10 col-lg-9 col-xl-12">
                    <div class="row">
                        {% for partner in partners %}
                            <div class="col-md-4 col-xl-2 mt-4"><a href="{{ partner.link }}"><img class="img-semi-transparent" src="{{ asset(partner.logoPath) }}" width="169" height="68" alt=""></a></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/about/history_ae.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Cпециальность СХМ
{% endblock %}
{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'mdi mdi-library-books',
        title: 'История'
    }) }}

    <section class="section novi-background section-98 section-sm-66">
        <div class="container">
            <h2>Cпециальность СХМ</h2>
            <hr class="divider bg-mantis mb-4">
            <div class="row justify-content-sm-center mt-0">
                <div class="col text-left">
                    <div class="offset-top-0 offset-lg-top-0">
                        <p>Специальность «Сельскохозяйственные машины и оборудование» была открыта в сентябре 1947 г. в Алтайском машиностроительном институте (АМИ), история которого началась на Алтае с 1942 года на базе эвакуированного в Барнаул Запорожского машиностроительного института. Тогда был организован первый набор 25 человек по специальности «Сельскохозяйственные машины» (первоначальное название специальности). Одновременно АМИ был преобразован в институт сельскохозяйственного машиностроения (АИСХМ).</p>
                        <p>Открытие этой специальности на Алтае было вызвано тем, что Алтай, да и страна в целом, нуждался в инженерных кадрах конструкторов для отрасли сельскохозяйственного машиностроения. И сегодня эта специальность остается остродефицитной, т.к. всего два вуза в стране готовят инженеров-конструкторов по этому профилю: АлтГТУ и Донской государственный технический университет. Первые наборы студентов на специальность почти на половину состояли из фронтовиков. Именно они задавали тон в учебе, демонстрируя серьезное отношение к делу, огромную целеустремленность и трудолюбие. Неслучайно, что каждый из них стал в последствии незаурядным инженером, крупным специалистом отрасли.</p>
                        <p>С открытием специальности создана и кафедра СХМ, на которой первоначально работал только ее заведующий, а в 1948 г. штат пополнился еще тремя преподавателями. В настоящее время на кафедре работают 10 преподавателей и 5 сотрудников.</p>
                        <p>Первым заведующим кафедры был к.т.н., доцент Грищенко Федор Васильевич, многое сделавший для становления кафедры и организации учебного процесса. С 1953 г. по 1963 г. кафедрой заведовал к.т.н., доцент Спичкин Ливерий Максимович. С 1964 г. по 1973 г. кафедрой заведовал к.т.н., доцент Ким Роман Александрович, добрейшей души человек, кладезь изобретательских идей. С 1973 г. по 1979 г. кафедрой заведовал к.т.н., доцент Болгов Алексей Трофимович. В эти годы возглавляемая им научно-исследовательская лаборатория НИЛ-4 наряду с исследованиями трансмиссии трактора занялась исследованием динамической нагруженности рабочих органов сельхозмашин. С 1979г. по 2007 г. время кафедрой заведовал д.т.н., профессор, заслуженный деятель науки и техники РФ, член-корреспондент академии инженерных наук РФ Семенов Владимир Филимонович.</p>
                        <p>До 1965 года при открытии кафедры ей первоначально было выделено несколько помещений под преподавательскую и лаборатории в старом здании института по улице Интернациональной. В 1970 г. кафедра переселилась в новый корпус «В», а в лабораторном корпусе «А» получила два больших помещения. В одном из них был оборудован машинный зал с почвенным каналом, а в другом силами преподавателей и студентов отстроен второй этаж и образованы учебные, научные лаборатории, мастерская, аудитории для проведения лекционных и практических занятий. Это позволило в лучшей мере организовать учебный процесс и повысить в конечном счете качество обучения.</p>
                        <p>Во время учебы студенты не только получают знания, предусмотренные учебным планом, но и принимают активное участие в научно-исследовательской работе, занимаются спортом, участвуют в студенческих строительных отрядах, художественной самодеятельности. Хорошей школой для студентов специальности явились механизированные отряды, которые выезжали на работы в сельские районы края во время технологической практики. Эти отряды принимали участие в освоении целинных и залежных земель, уборке урожая сельскохозяйственных культур.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/about/history_ct.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Кафедра автомобилей и тракторов
{% endblock %}
{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'mdi mdi-library-books',
        title: 'История'
    }) }}

    <section class="section novi-background section-98 section-sm-66">
        <div class="container">
            <h2>Кафедра автомобилей и тракторов</h2>
            <hr class="divider bg-mantis mb-4">
            <div class="row justify-content-sm-center mt-0">
                <div class="col text-left">
                    <div class="offset-top-0 offset-lg-top-0">
                        <p>Кафедра «Автомобили и тракторы»,  вошедшая в состав кафедры НТТС в 2014г. была одной из старейших кафедр университета, она была создана в апреле 1944 года через два года после начала учебных занятий во вновь созданном первым на Алтае техническом вузе, образованном на базе эвакуированного Запорожского машиностроительного института.</p>
                        <p>К осени 1942 года были укомплектованы все 5 курсов института и, в том числе, 4-й курс по «Автотракторной» специальности. На первые 3 курса были зачислены 77 студентов Московского автомеханического института МАМИ, которые составили ядро контингента автотракторного факультета.</p>
                        <img width="200" height="900" class="mr-3 img-fluid d-inline-block float-sm-left" src="{{ asset('images/barski.png') }}" alt="">
                        <p>Первым заведующим кафедрой был Игорь Борисович Барский — выпускник бронетанковой академии и аспирантуры МАМИ, впоследствии д.т.н., профессор, автор ряда монографий и учебников по расчету и конструированию тракторов; по существу — основоположник кафедры.</p>
                        <p>Это было тяжелое время. Шла война. Жизнь и учеба впроголодь в неотапливаемых помещениях, работа на сборке трактора из утиля, чтобы вспахать поле под картошку для студенческой столовой, заготовка дров. Каникул нет – работа на уборке урожая или в подсобном хозяйстве. И тем не менее, студенты активно участвуют в общественной жизни института: Ибрагимов А. и Майданский Я. — поочередно возглавляют комитет ВЛКСМ, Толчинский Н. – бессменный редактор институтских стенгазет, Троицкий Б. – организатор художественной самодеятельности, Владимиров А. – руководитель оркестра народных инструментов.</p>
                        <p class="float-none">Выпуск первого набора успешно прошел осенью 1944 года. Молодые специалисты уехали восстанавливать Харьковский тракторный завод, строить Липецкий и Владимирский тракторные заводы, а часть из них была направлена для работы на промышленные предприятия Алтайского края, причем потребность в инженерах-механиках в послевоенный период была настолько велика, что выпускники кафедры успешно работали не только на предприятиях автотракторного направления, но и на различных машиностроительных заводах. Вот имена первых выпускников «Автотракторной» специальности: М. Бандуровская, Ф. Белецкая, Н. Борисенко, Л. Гольберг, А. Дармодехия, И. Жоголев, А. Ибрагимов, В. Мацковский Ф. Полякова, Н. Скрипец, П. Склянникова, Н. Толчинский, Б. Троицкий.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/about/partners.html.twig
{% block title %}
Партнеры
{% endblock %}
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'icon-md mdi mdi-wrench',
        title: 'Партнеры'
    }) }}

    <!-- Our Customers-->
    <section class="section novi-background section-98 section-sm-110 section-sm-top-50">
        <div class="container">
            <h1>Партнеры по производственной практике</h1>
            <hr class="divider bg-mantis">
            <div class="row justify-content-sm-center align-items-xl-center offset-top-66">
                <div class="col-md-10 col-lg-9 col-xl-12">
                    <div class="row">
                        {% for partner in partners %}
                            <div class="col-md-4 col-xl-2 mt-4"><a href="{{ partner.link }}"><img class="img-semi-transparent" src="{{ asset(partner.logoPath) }}" width="169" height="68" alt=""></a></div>
                        {% endfor %}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}