src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Вы уже регестрировались!"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups("main")
     * @Assert\NotBlank(message="Введите email")
     * @Assert\Email(message="Введите корректный email")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\News", mappedBy="author", orphanRemoval=true)
     */
    private $news;

    /**
     * @ORM\Column(type="datetime")
     */
    private $agreedTermsAt;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photoFilename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $post;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $academicDegree;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __construct()
    {
        $this->news = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed for apps that do not check user passwords
        // not needed when using bcrypt or argon
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAvatarUrl(int $size = null): string
    {
        $url = 'https://robohash.org/'.$this->getEmail();
        if ($size) {
            $url .= sprintf('?size=%dx%d', $size, $size);
        }
        return $url;
    }

    /**
     * @return Collection|News[]
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(News $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news[] = $news;
            $news->setAuthor($this);
        }

        return $this;
    }

    public function removeNews(News $news): self
    {
        if ($this->news->contains($news)) {
            $this->news->removeElement($news);
            // set the owning side to null (unless already changed)
            if ($news->getAuthor() === $this) {
                $news->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->firstName;
    }

    public function getAgreedTermsAt(): ?\DateTimeInterface
    {
        return $this->agreedTermsAt;
    }

    public function agreeTerms(): self
    {
        $this->agreedTermsAt = new \DateTime();
        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $telephone): self
    {
        $this->phoneNumber = $telephone;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(?string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getPhotoFilename(): ?string
    {
        return $this->photoFilename;
    }

    public function setPhotoFilename(?string $photoFilename): self
    {
        $this->photoFilename = $photoFilename;

        return $this;
    }

    public function getPhotoPath(): ?string
    {
        return  $this->getPhotoFilename() ? 'images/users/'.$this->getPhotoFilename() : null;
    }

    public function getPost(): ?string
    {
        return $this->post;
    }

    public function setPost(string $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getAcademicDegree(): ?string
    {
        return $this->academicDegree;
    }

    public function setAcademicDegree(?string $academicDegree): self
    {
        $this->academicDegree = $academicDegree;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

}

src/Controller/StaffController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class StaffController extends BaseController
{
    /**
     * @Route("/staff", name="app_staff_list")
     * @param UserRepository $userRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function staffList(UserRepository $userRepository, Request $request)
    {
        $this->contactUsHandleForm($request);
        $staff = $userRepository->findAllStaff();
        return $this->render('staff/list.html.twig', [
            'staff' => $staff,
        ]);
    }

    /**
     * @Route("/curators", name="app_curators")
     */
    public function curatorsList(Request $request)
    {
        $this->contactUsHandleForm($request);
        return $this->render("staff/curators.html.twig");
    }

    /**
     * @Route("/staff/{email}", name="app_member_show")
     */
    public function showMember(User $user, Request $request)
    {
        $this->contactUsHandleForm($request);
        return $this->render("staff/member.html.twig", [
            'user' => $user
        ]);
    }

    /**
     * @Route("/research-and-evelopment", name="app_niokr")
     */
    public function showNiokrInformation(Request $request)
    {
        $this->contactUsHandleForm($request);
        return $this->render("staff/niokr.html.twig");
    }
}

templates/staff/curators.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Кураторы
{% endblock %}


{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'icon-lg mdi mdi-account-multiple-outline',
        title: 'Кураторы'
    }) }}

    <!-- Classic Responsive Table-->
    <section class="section novi-background section-4неизвестно section-md-bottom-85 section-sm-top-66">
        <div class="container">
            <h4>Связаться с кураторами можно по телефону <span class="text-primary">290−815</span></h4>
            <div class="row offset-md-top-24">
                <div class="offset-xl-3 col-xl-6 ">
                    <!-- Classic Responsive Table-->
                    <div class="table-responsive-sm">
                        <table class="table table-custom table-bordered">
                            <thead class="thead-dark">
                            <tr>
                                <th>Курс</th>
                                <th>Группа</th>
                                <th>Куратор</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/staff/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Сотрудники{% endblock %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'icon-lg mdi mdi-account-box-outline',
        title: 'Сотрудники'
    }) }}

    <!-- Our Team-->
    <section class="section novi-background section-41 section-sm-20 mb-md-5">
        <div class="container">
            <div class="row justify-content-sm-center text-center text-lg-left offset-top-30">
                {% for user in staff %}
                <div class="col-md-5 col-lg-3 offset-top-50"><img class="img-fluid d-inline-block" src="{{ asset(user.getPhotoPath) }}" width="270" height="270" alt="">
                    <div class="text-lg-left offset-top-20">
                        <div>
                            <h5 class="font-weight-bold text-primary"><a href="{{ path('app_member_show', {email: user.email}) }}">{{ user.firstName }}</a></h5>
                        </div>
                    </div>
                    <address class="contact-info text-lg-left">
                        <ul class="list-unstyled p">
                            <li><span class="icon novi-icon icon-xxs mdi mdi-phone text-middle"></span> <a class="d-inline-block text-middle" href="tel:1-800-7650-986">{{ user.phoneNumber }}</a>
                            </li>
                            <li><span class="icon novi-icon icon-xxs mdi mdi-email-open text-middle"></span> <a class="d-inline-block text-middle" href="mailto:{{ user.email }}">{{ user.email }}</a>
                            </li>
                            <li><span class="icon novi-icon icon-xxs mdi mdi-map-marker-circle text-middle"></span><span class="d-inline-block text-middle">{{ user.position }}</span>
                            </li>
                        </ul>
                    </address>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

templates/staff/member.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'icon-lg mdi mdi-account-box',
        title: 'Сотрудник'
    }) }}

    <!-- Section John Doe-->
    <section class="section novi-background section-98 section-sm-110 section-sm-bottom-34">
        <div class="container">
            <div class="row justify-content-sm-center">
                <div class="col-sm-10 col-md-5 col-xl-4 text-lg-left">
                    <!-- Member Block Type 5-->
                    <div class="member-block-type-5 inset-lg-right-30"><img class="img-fluid d-block mx-auto" src="{{ asset(user.photoPath)}}" width="437" height="437" alt="">
                        <div class="member-block-body text-center"><a class="btn btn-block btn-primary" href="contact-me.html">Free consultation</a>
                            <div class="offset-top-24 offset-lg-top-20 text-center">
                                <div><span class="novi-icon icon icon-xxs text-middle mdi mdi-cellphone-android text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="tel:{{ user.phoneNumber }}">{{ user.phoneNumber }}</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-email-open text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="mailto:{{ user.email }}">{{ user.email }}</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-map-marker-circle"></span>&ensp;<span class="text-middle text-dark">{{ user.position }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 text-md-left col-md-7 col-xl-8 offset-top-24 offset-md-top-0">
                    <h3>{{ user.firstName }}</h3>
                    <div>
                        <h3 class="small text-darker">{{ user.post }}</h3>
                        <p class="small text-darker">{{ user.academicDegree }}</p>
                    </div>
                    <hr class="text-subline offset-top-10 offset-md-top-30">
                    <div class="offset-top-24 offset-lg-top-50 text-left">
                        {{ user.description }}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Timeline-->
    <section class="section novi-background section-98 section-sm-41 bg-lightest">
        <div class="container text-md-left">
            <h3 class="text-picton-blue text-center">Основные научные труды</h3>
            <hr class="hr bg-gray">
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
            <div class="row justify-content-sm-center text-left">
                <div class="col offset-top-14 offset-md-top-0">
                    <p><span class="font-weight-bold text-primary">1.&nbsp;&nbsp;</span>John is a #1 New York Times bestselling author. With more than 1 million copies collectively in print, his seven books on personal finance have been translated into several languages and educated countless people worldwide. The Truth About Money was recognized with an Excellence in Financial Literacy Education (EIFLE) Book of the Year Award from the Institute for Financial Literacy (March 2007), a Gold Medal Axiom Award (March 2008), an Apex Award (June 2007), and was named Book of the Year by Small Press magazine (1997). The Lies About Money was awarded the Axiom Personal Finance Book of the Year (March 2008) and an EIFLE Award (Jan. 2009). John's eighth book, The Truth About Retirement Plans and IRAs, a #1 national best-seller, was published in April 2009.</p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/staff/niokr.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Научно-исследовательские и опытно-конструкторские работы
{% endblock %}
{% block body %}

    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-connectdevelop',
        title: 'НИОКР'
    }) }}

    <section class="section novi-background section-98 section-bottom-41 section-sm-110">
        <div class="container">
            <div class="row justify-content-sm-center">
                <div class="col-sm-10 col-md-5 col-xl-4 text-lg-left">
                    <!-- Member Block Type 5-->
                    <div class="member-block-type-5 inset-lg-right-30"><img class="img-fluid d-block mx-auto" src="{{ asset('images/users/user-john-doe-437x437.jpg') }}" width="437" height="437" alt="">
                        <div class="member-block-body text-center"><a class="btn btn-block btn-primary" href="#">Подробнее</a>
                            <div class="offset-top-24 offset-lg-top-20 text-center">
                                <div><span class="novi-icon icon icon-xxs text-middle mdi mdi-cellphone-android text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="tel:#">8 (3852) 29-09-42</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-email-open text-darker"></span>&ensp;<span class="text-middle"><a class="text-dark" href="mailto:#">skb-altstu@mail.ru</a></span>
                                </div>
                                <div class="pt-1"><span class="novi-icon icon icon-xxs text-middle mdi mdi-map-marker-circle"></span>&ensp;<span class="text-middle text-dark">Аудитория: 202 В</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-10 text-md-left col-md-7 col-xl-8 offset-top-24 offset-md-top-0">
                    <h3>Сороченко Сергей Федорович</h3>
                    <div>
                        <h3 class="small text-darker">ГЛАВНЫЙ СПЕЦИАЛИСТ</h3>
                        <p class="small text-darker">доктор теxнических наук, доцент</p>
                    </div>
                    <hr class="text-subline offset-top-10 offset-md-top-30">
                    <div class="offset-top-24 offset-lg-top-0">
                        <p class="text-left">
                            Студенческое конструкторское бюро (СКБ) является структурным подразделением инновационно-технологического центра (ИТЦ) научно-инновационного управления (НИУ) федерального государственного бюджетного образовательного учреждения высшего профессионального образования «Алтайский государственный технический университет им. И.И. Ползунова» (АлтГТУ).

                            В своей деятельности СКБ руководствуется Уставом АлтГТУ, его актами и настоящим Положением.
                            Студенческое конструкторское бюро (СКБ) является структурным подразделением инновационно-технологического центра (ИТЦ) научно-инновационного управления (НИУ) федерального государственного бюджетного образовательного учреждения высшего профессионального образования «Алтайский государственный технический университет им. И.И. Ползунова» (АлтГТУ).

                            В своей деятельности СКБ руководствуется Уставом АлтГТУ, его актами и настоящим Положением.

                            Сотрудниками СКБ могут быть студенты, магистранты, аспиранты и сотрудники АлтГТУ, а также опытные специалисты сторонних организаций.

                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-bottom-41 novi-background one-page">
            <div id="particles-container"></div>
            <div class="container">
                <h3 class="text-center">Подробная информация</h3>
                <hr class="divider divider-md bg-mantis">
                <div class="row justify-content-sm-center align-items-sm-center">
                    <div class="col-sm-6 text-left">
                        СКБ своей деятельностью способствует:
                        развитию у студентов, магистрантов и аспирантов научно-технического творчества и навыков в проектировании техники, на научной основе организовать свой труд, самостоятельно оценивать результаты своей деятельности, владеть навыками самостоятельной работы, в том числе в сфере проектирования и проведения научных исследований;
                        материально-технической поддержке молодёжных проектов;
                        закреплению творческого подхода студентов к будущей профессиональной деятельности;
                        приобретению навыков и умений студентов работы в коллективе над инновационными проектами, в управлении структурным подразделением организации, работе с персоналом.
                        СКБ осуществляет хоздоговорную деятельность в структуре ИТЦ НИУ университета на условиях хозрасчётного функционального подразделения.
                        СКБ осуществляет свою деятельность на площадях АлтГТУ, закреплённых за ним приказом ректора.
                    </div>
                    <div class="col-sm-6 text-left">
                        СКБ своей деятельностью способствует:
                        развитию у студентов, магистрантов и аспирантов научно-технического творчества и навыков в проектировании техники, на научной основе организовать свой труд, самостоятельно оценивать результаты своей деятельности, владеть навыками самостоятельной работы, в том числе в сфере проектирования и проведения научных исследований;
                        материально-технической поддержке молодёжных проектов;
                        закреплению творческого подхода студентов к будущей профессиональной деятельности;
                        приобретению навыков и умений студентов работы в коллективе над инновационными проектами, в управлении структурным подразделением организации, работе с персоналом.
                        СКБ осуществляет хоздоговорную деятельность в структуре ИТЦ НИУ университета на условиях хозрасчётного функционального подразделения.
                        СКБ осуществляет свою деятельность на площадях АлтГТУ, закреплённых за ним приказом ректора.
                    </div>
                    <div class="col-12">
                        СКБ участвует в научно-технических молодёжных программах, выставках, конкурсах, конференциях федерального, регионального и университетского уровня.

                        СКБ представляет в НИУ ежегодный отчёт о своей деятельности, имеет страницу на сайте университета.
                    </div>
                </div>
            </div>
    </section>
{% endblock %}