src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Придумайте заголовок!")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})  // автоматическая генерация slug уникального
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message="Введите содержимое новости!")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $viewsCount = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="news")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="news")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Выберите автора!")
     */
    private $author;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function isPublished(): bool
    {
        return $this->publishedAt !== null;
    }

    public function getViewsCount(): ?int
    {
        return $this->viewsCount;
    }

    public function setViewsCount(int $viewsCount): self
    {
        $this->viewsCount = $viewsCount;

        return $this;
    }

    public function incrementViewsCount(): self
    {
        $this->viewsCount = $this->viewsCount + 1;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
    public function getImagePath()
    {
        return 'images/news/'.$this->getImageFilename();
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

}

src/Controller/NewsAdminController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Form\NewsFormType;
use App\Repository\NewsRepository;
use App\Service\FileLoader;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class NewsAdminController
 * @package App\Controller
 */
class NewsAdminController extends BaseController
{
    /**
     * @Route("admin/news/new", name="admin_news_new")
     * @IsGranted("ROLE_AUTHOR")
     */
    public function new(Request $request, EntityManagerInterface $em, FileLoader $fileLoader, $newsImageDirectory)
    {
        $form = $this->createForm(NewsFormType::class, null, [
            'admin_rights' => $this->isGranted("ROLE_ADMIN"),
        ]);
        $form['author']->setData($this->getUser());

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var News $news */
            $news = $form->getData();

            /** @var UploadedFile $image */
            $image = $form['image']->getData();

            if ($image) {
                $imageFileName = $fileLoader->upload($image, $newsImageDirectory);
                $news->setImageFilename($imageFileName);
            }

            $news->setAuthor($this->getUser());

            $em->persist($news);
            $em->flush();

            $this->addFlash('success', 'Новая новость добавлена, смотрите список ваших новостей ниже');

            return $this->redirectToRoute('app_account');
        }

        $this->contactUsHandleForm($request);

        return $this->render('news_admin/new.html.twig', [
            'newsForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/news/list", name="admin_news_list")
     * @param NewsRepository $newsRepository
     * @return Response
     * @IsGranted("ROLE_ADMIN")
     */
    public function list(NewsRepository $newsRepository, Request $request)
    {
        $news_list = $newsRepository->findAll();

        $this->contactUsHandleForm($request);
        return $this->render('news_admin/list.html.twig', [
            'news_list' => $news_list,
        ]);
    }


    /**
     * @Route("author/news/{id}/edit", name="author_news_edit")
     * @IsGranted("MANAGE", subject="news")
     */
    public function edit(News $news, Request $request, EntityManagerInterface $em, FileLoader $fileLoader, $newsImageDirectory)
    {
        $form = $this->createForm(NewsFormType::class, $news, [
            'admin_rights' => $this->isGranted("ROLE_ADMIN"),
        ]);

        if ($news->getImageFilename()) {
            $form['image']->setData(new File($newsImageDirectory.'/'.$news->getImageFilename()));
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $image */
            $image = $form['image']->getData();

            if ($image) {
                $imageFileName = $fileLoader->upload($image, $newsImageDirectory);
                $news->setImageFilename($imageFileName);
            }

            $em->persist($news);
            $em->flush();

            $this->addFlash('success', 'Новость отредактирована, проверьте её ещё раз!');

            return $this->redirectToRoute('news_show', [
                'slug' => $news->getSlug()
            ]);
        }

        $this->contactUsHandleForm($request);
        return $this->render('news_admin/edit.html.twig', [
            'newsForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/author/news/{id}/delete", name="author_news_delete")
     * @IsGranted("MANAGE", subject="news")
     */
    public function delete(News $news, EntityManagerInterface $em)
    {
        $em->remove($news);
        $em->flush();

        $this->addFlash('success', 'Новость успешно удалена!');

        return $this->redirectToRoute('app_account');
    }

}

templates/news_admin/_form.html.twig
{{ form_start(newsForm, {
    'attr': {
        'class': 'text-left',
        'data-form-output': 'form-output-global',
        'data-form-type': 'contact'
    }
}) }}
    <div class="row">
        <div class="col-xl-6">
            <div class="form-group">
                {{ form_errors(newsForm.title) }}
                {{ form_widget(newsForm.title, {
                    'attr': {
                        'class': 'form-control',
                        'data-constraints':'@Required',
                        'placeholder': 'Заголовок'
                    }
                }) }}
            </div>
        </div>

        <div class="col-xl-6">
            <div class="form-group">
                {{ form_errors(newsForm.author) }}
                {{ form_widget(newsForm.author, {
                    'attr': {
                        'class': 'form-control js-autocomplete',
                        'data-constraints':'@Required',
                        'placeholder': 'Автор'
                    }
                }) }}
            </div>
        </div>

        <div class="col-xl-12 offset-top-20">
            <div class="form-group">
                {{ form_errors(newsForm.content) }}
                {{ form_widget(newsForm.content, {
                    'attr': {
                        'class': 'form-control',
                        'data-constraints':'@Required',
                        'placeholder': 'Содержание'
                    }
                }) }}
            </div>
        </div>
        <div class="col-xl-12 offset-top-20">
            <div class="form-group">
                {{ form_errors(newsForm.image) }}
                {{ form_widget(newsForm.image, {
                    'attr': {
                        'placeholder': 'Изображение',
                        'class': 'form-control',
                    }
                }) }}
            </div>
        </div>
        {% if newsForm.publishedAt is defined%}
        <div class="col-xl-12 offset-top-20">
            <div class="form-group">
                {{ form_label(newsForm.publishedAt, 'Дата публикации:') }}
                {{ form_widget(newsForm.publishedAt, {
                    'attr': {
                        'class': 'form-control',
                        'data-constraints':'@Required'
                    }
                }) }}
            </div>
        </div>
        {% endif %}
        {% if newsForm.tags is defined %}
            <div class="col-xl-12 offset-top-20">
                <div class="form-group">
                    {{ form_label(newsForm.tags, 'Теги:') }}
                    {{ form_widget(newsForm.tags, {
                        'attr': {
                            'class': 'form-control',
                            'data-constraints':'@Required',
                        }
                    }) }}
                </div>
            </div>
        {% endif %}
    </div>
<div class="group-sm text-center text-xl-left offset-top-30">
    <button class="btn btn-primary" type="submit">{{ button_text }}</button>
    <button class="btn btn-default" type="reset">Отмена</button>
</div>
{{ form_end(newsForm) }}

templates/news_admin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script>
    <script src="{{ asset('js/algolia-autocomplete.js') }}"></script>
{% endblock %}

{% block stylesheet %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/algolia-autocomplete.css') }}">
{% endblock %}

{% block body %}

    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-pencil-square',
        title: 'Редактировать новость'
    }) }}

    <!-- Manage news-->
    <section class="section section-98 section-md-66 text-xl-left">
        <div class="container">
            <div class="row justify-content-sm-center justify-content-sm-center">
                <div class="col-xl-4">
                    <h3 class="text-uppercase">Подсказка</h3>
                    <hr class="divider hr-xl-left-0 bg-mantis">
                    <p>If you have any questions, just fill in the contact form, and we will answer you shortly. If you are living nearby, come visit Intense in one of our comfortable offices.</p>
                    <address class="contact-info offset-top-50">
                        <p class="h6 text-uppercase font-weight-bold text-picton-blue letter-space-none offset-top-none">Intense Office 1</p>
                        <p>9863 - 9867 MILL ROAD, CAMBRIDGE, MG09 99HT.</p>
                        <dl class="offset-top-0">
                            <dt>Telephone</dt>
                            <dd><a href="tel:#">+1 800 603 6035</a></dd>
                        </dl>
                        <dl>
                            <dt>E-mail:</dt>
                            <dd><a href="mailto:#">mail@demolink.org</a></dd>
                        </dl>
                    </address>
                    <address class="contact-info offset-top-50">
                        <p class="h6 text-uppercase font-weight-bold text-picton-blue letter-space-none">Intense Office 2</p>
                        <p>9870 ST VINCENT PLACE, GLASGOW, DC 45 FR 45.</p>
                        <dl class="offset-top-0">
                            <dt>Telephone</dt>
                            <dd><a href="tel:#">+1 800 559 6580</a></dd>
                        </dl>
                        <dl>
                            <dt>E-mail:</dt>
                            <dd><a href="mailto:#">mail@demolink.org</a></dd>
                        </dl>
                    </address>
                </div>
                <div class="col-md-8 offset-top-66 offset-xl-top-0">
                    <h3 class="text-uppercase">Заполните поля</h3>
                    <hr class="divider hr-xl-left-0 bg-mantis">
                    <!-- RD Mailform-->
                    {{ include('news_admin/_form.html.twig', {
                        button_text: 'Подтвердить'
                    }) }}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/news_admin/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
 Список новостей
{% endblock %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-table',
        title: 'Список всех новостей'
    }) }}

    <!-- Classic Responsive Table-->
    <section class="section novi-background section-66 section-sm-top-20">
        <div class="container">
            <div class="row offset-md-top-66">
                <div class=" col-xl">
                    <!-- Classic Responsive Table-->
                    <table class="table table-custom table-bordered" data-responsive="true">
                        <tr>
                            <th>Название</th>
                            <th>Автор</th>
                            <th>Email</th>
                            <th>Опубликована?</th>
                            <th class="text-center">Edit</th>
                        </tr>
                        {% for news in news_list %}
                            <tr>
                                <td><a class="text-primary" href="{{ path('news_show', {slug: news.slug}) }}">{{ news.title }}</a></td>
                                <td>{{ news.author.firstName }}</td>
                                <td>{{ news.author.email }}</td>
                                <td class="text-center"><i class="novi-icon icon-xs fa fa-{{ news.published ? 'check text-success' : 'close' }}"></i></td>
                                <td class="text-xs-center">
                                    <a href="{{ path('author_news_edit', {
                                        id: news.id
                                    }) }}"><i class="btn btn-info fa fa-pencil"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/news_admin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Создать новость{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script>
    <script src="{{ asset('js/algolia-autocomplete.js') }}"></script>
{% endblock %}

{% block stylesheet %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/algolia-autocomplete.css') }}">
{% endblock %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-pencil-square-o',
        title: 'Создать новость'
    }) }}

    <!-- Contact Us-->
    <section class="section section-98 section-md-66 text-xl-left">
        <div class="container">
            <div class="row justify-content-sm-center justify-content-sm-center">
                <div class="col-xl-4">
                    <h3 class="text-uppercase">Подсказка</h3>
                    <hr class="divider hr-xl-left-0 bg-mantis">
                    <p>If you have any questions, just fill in the contact form, and we will answer you shortly. If you are living nearby, come visit Intense in one of our comfortable offices.</p>
                    <address class="contact-info offset-top-50">
                        <p class="h6 text-uppercase font-weight-bold text-picton-blue letter-space-none offset-top-none">Intense Office 1</p>
                        <p>9863 - 9867 MILL ROAD, CAMBRIDGE, MG09 99HT.</p>
                        <dl class="offset-top-0">
                            <dt>Telephone</dt>
                            <dd><a href="tel:#">+1 800 603 6035</a></dd>
                        </dl>
                        <dl>
                            <dt>E-mail:</dt>
                            <dd><a href="mailto:#">mail@demolink.org</a></dd>
                        </dl>
                    </address>
                    <address class="contact-info offset-top-50">
                        <p class="h6 text-uppercase font-weight-bold text-picton-blue letter-space-none">Intense Office 2</p>
                        <p>9870 ST VINCENT PLACE, GLASGOW, DC 45 FR 45.</p>
                        <dl class="offset-top-0">
                            <dt>Telephone</dt>
                            <dd><a href="tel:#">+1 800 559 6580</a></dd>
                        </dl>
                        <dl>
                            <dt>E-mail:</dt>
                            <dd><a href="mailto:#">mail@demolink.org</a></dd>
                        </dl>
                    </address>
                </div>
                <div class="col-md-8 offset-top-66 offset-xl-top-0">
                    <h3 class="text-uppercase">Заполните поля</h3>
                    <hr class="divider hr-xl-left-0 bg-mantis">
                    <!-- RD Mailform-->
                    {{ include('news_admin/_form.html.twig', {
                        button_text: 'Создать'
                    }) }}
                </div>
            </div>
        </div>
    </section>

{% endblock %}