src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Придумайте заголовок!")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})  // автоматическая генерация slug уникального
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message="Введите содержимое новости!")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $viewsCount = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="news")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="news")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Выберите автора!")
     */
    private $author;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function isPublished(): bool
    {
        return $this->publishedAt !== null;
    }

    public function getViewsCount(): ?int
    {
        return $this->viewsCount;
    }

    public function setViewsCount(int $viewsCount): self
    {
        $this->viewsCount = $viewsCount;

        return $this;
    }

    public function incrementViewsCount(): self
    {
        $this->viewsCount = $this->viewsCount + 1;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
    public function getImagePath()
    {
        return 'images/news/'.$this->getImageFilename();
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

}

src/Controller/NewsController.php
<?php


namespace App\Controller;


use App\Entity\News;
use App\Form\ContactUsFormType;
use App\Form\Model\ContactUsFormModel;
use App\Repository\NewsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Cookie;

class NewsController extends BaseController
{
    /**
     * @Route("/", name="app_home")
     * @param NewsRepository $repository
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function homepage(NewsRepository $repository, PaginatorInterface $paginator, Request $request)
    {
        $queryBuilder = $repository->getAllPublishedQueryBuilder();
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            6
        );
        $this->contactUsHandleForm($request);

        return $this->render('home/home.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/news/{slug}", name="news_show")
     * @param News $news
     * @return Response
     */
    public function show(News $news, Request $request, EntityManagerInterface $em)
    {
        $this->contactUsHandleForm($request);

        if (!$request->cookies->has($news->getSlug().'views')) {
            $response = new Response();
            $response->headers->setCookie(Cookie::create($news->getSlug().'views', 'viewed', time()+2592000));
            $news->incrementViewsCount();
            $em->flush();
        }

        return $this->render('news/show.html.twig', [
            'news' => $news,
        ], $response ?? null);
    }

    /**
     * @Route("/newslist", name="news_list")
     * @param NewsRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function show_all(NewsRepository $repository, PaginatorInterface $paginator, Request $request ) {
        $queryBuilder = $repository->getAllPublishedQueryBuilder();
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            9
        );

        $this->contactUsHandleForm($request);
        return $this->render('news/list.html.twig', [
            'pagination' => $pagination,
        ]);
    }
}

templates/news/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Все новости{% endblock title %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'mdi mdi-newspaper',
        title: 'Все Новости'
    }) }}

<section class="section novi-background section-bottom-66 section-sm-bottom-110 section-top-34 section-md-top-66" style="background-color: rgb(255, 255, 255);">
        <div class="container">
            <div class="row">

                {% for news in pagination %}
                <div class="col-md-6 col-lg-4"><img class="img-fluid d-inline-block" src="{{ asset(news.imagePath) }}" width="370" height="230" alt="">
                    <div class="text-md-left offset-top-24">
                        <div>
                            <h5 class="font-weight-bold text-primary"><a href="{{ path('news_show', { slug: news.slug}) }}">{{ news.title }}</a></h5></div>
                        <h6 class="offset-top-10">{{ news.publishedAt ? news.publishedAt|date('Y-m-d') }}</h6>
                        <ul class="list-inline list-inline-dashed text-dark">
                          {% for tag in news.tags %}
                             <li class="list-inline-item">{{ tag.name }}</li>
                          {% endfor %}
                        </ul>
                        <div>
                            <p>{{ news.content|truncate(200)|markdown }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            <div class="offset-top-20 offset-md-top-34 pagination justify-content-center">
            <!— Bootstrap Pagination-->
                 {{ knp_pagination_render(pagination) }}
             </div>
        </div>
    </section>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('js/news_show.js') }}"></script>
{% endblock javascripts %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ news.title }}{% endblock title %}

{% block body %}
    {{ include('layouts/breadcrumbs.html.twig', {
        icon: 'fa fa-file-text-o',
        title: 'Новость'
    }) }}

        <section class="section novi-background section-98 section-sm-110">
            <div class="container">
                <div class="row justify-content-sm-center">
                    <div class="col-sm-10 col-xl-6 text-lg-left inset-lg-right-80">
                        <h2>{{ news.title }}</h2>
                        <hr class="text-subline offset-top-10 offset-md-top-10">
                        <ul class="list-inline list-inline-dashed text-dark">
                            {% for tag in news.tags %}
                                <li class="list-inline-item">{{ tag.name }}</li>
                            {% endfor %}
                        </ul>
                        {#  todo                  <span class="small js-like-news-count">{{ news.heartCount }}</span>#}
                        {#                    <a href="{{ path('news_toggle_heart', {slug: news.slug}) }}" class="far fa-heart-o js-like-news" style="color:red;"></a>#}
                        {#                    <span class="small">Views:{{ news.viewsCount }}</span>#}

                        <div class="offset-top-10 offset-lg-top-10">
                            {{ news.Content|cached_markdown }}
                        </div>
                    </div>
                    <div class="col-sm-10 col-xl-6 offset-top-10 offset-xl-top-0">
                        <img class="img-fluid d-inline-block offset-top-10" src="{{ asset(news.imagePath) }}" width="960" height="540" alt="">


                        <div class="text-left text-dark offset-top-10 ml-1">
                            <div>
                                <ul class="post-controls list-inline list-inline-sm p text-dark">
                                    <li class=""><span class="text-middle icon-xxs novi-icon text-picton-blue mdi mdi-account-outline">&nbsp;</span><a class="text-middle small" href="{{ path('app_member_show', {email: news.author.email}) }}">{{ news.author }}</a></li>
                                    {% if is_granted('MANAGE', news) %}
                                        <li class=""><span class="text-middle icon-xxs novi-icon text-picton-blue mdi fa fa-pencil">&nbsp;</span><a class="text-middle small" href="{{ path('author_news_edit', {id: news.id}) }}">Редактировать</a></li>
                                        <li class=""><span class="text-middle icon-xxs novi-icon text-picton-blue mdi mdi-delete">&nbsp;</span><a class="text-middle small" href="{{ path('author_news_delete', {id: news.id}) }}">Удалить</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <div><span class="text-middle icon-xxs novi-icon text-picton-blue mdi mdi-clock"></span>
                                <time class="text-middle small">{{ news.publishedAt ? news.publishedAt|ago : 'unpublished' }}</time>
                            </div>
                            <div><span class="text-middle icon-xxs novi-icon text-picton-blue mdi mdi-eye"></span>
                                <span class="text-middle small">{{ news.viewsCount }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('js/news_show.js') }}"></script>
{% endblock javascripts %}